### ISSUE TITLE
Can you check my iSSB pull request?

### ISSUE THREAD

**Issue by Alekemon** [lufinkey/data-cpp#1]
I already tested them. It's Samus and 2 stages. I worked hard on it.

**Comment by lufinkey** [comment]
Yeah I'm sorry, I've been really busy I'll try to make some time to pull it

**Comment by lufinkey** [comment]
In the future, please don't open issues on unrelated repositories like this though

**Comment by Alekemon** [comment]
Sorry, I've just been nervous. I won't do this again...

**Comment by lufinkey** [comment]
I understand, I'm really sorry for not being more responsive
